import Head from "next/head";

import Header from "../components/Header";
import Banner from "../components/Banner";

interface ExploreData {
  img: string;
  location: string;
  distance: string;
}

interface HomeProps {
  exploreData: ExploreData[];
}

const Home: React.FC<HomeProps> = ({ exploreData }) => {
  return (
    <div>
      <Head>
        <title>Airbnb</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Banner />

      <main className="max-w-7xl mx-auto px-8 sm:px-16">
        <section className="pt-6">
          <h2 className="text-4xl font-semibold pb-5">Explore Nearby</h2>

          {exploreData.map((item) => (
            <h1>{item.location}</h1>
          ))}
        </section>
      </main>
    </div>
  );
};

export default Home;

export async function getStaticProps(): Promise<{ props: HomeProps }> {
  const exploreData: ExploreData[] = await fetch(
    "https://links.papareact.com/pyp"
  ).then((res) => res.json());

  return {
    props: {
      exploreData,
    },
  };
}
